server {
    listen 80;

    location / {
        access_by_lua_block {
            local limit_req = require "resty.limit.req"

            local rate = 5      -- RPS
            local burst = 10    -- burst
            local dict = ngx.shared.login_limit

            local lim, err = limit_req.new("login_limit", rate, burst)
            if not lim then
                ngx.log(ngx.ERR, "failed to instantiate a limiter: ", err)
                return ngx.exit(500)
            end

            local login = ngx.req.get_headers()["login"]
            if not login then
                ngx.status = 400
                ngx.say("Missing login header")
                return ngx.exit(400)
            end

            local delay, err = lim:incoming(login, true)
            if not delay then
                if err == "rejected" then
                    ngx.status = 429
                    ngx.say("Too Many Requests for ", login)
                    return ngx.exit(429)
                else
                    ngx.log(ngx.ERR, "failed to limit request: ", err)
                    return ngx.exit(500)
                end
            end

            if delay >= 0.001 then
                ngx.sleep(delay)
            end
        }

        proxy_pass http://python:5000;
    }
}